### ISSUE TITLE
Error Running Recognize.py script

### ISSUE THREAD

**Issue by Aashima-Gupta** [GokulNC/OpenCV-Facial-Detection-and-Recognition#1]
Hi,
Q1. Initially i have captured 3 images as instructed in the data Set, i have trained them also, however whilr running the Recognize.py file through command line as **python Recognizer.py webcam** it always shows this error : 
**Press 'q' to quit

Traceback (most recent call last):
  File "Recognizer.py", line 150, in <module>
    predictFacesFromPhoto(testImage)
  File "Recognizer.py", line 18, in predictFacesFromPhoto
    img_gray = Image.open(image).convert('L')
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2622, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'Recognizer.py'**

**Here i want recognition from webCam only, why it is not going in the predictFacesFromWebcam(label_name_map)??**

Q2. What is **label_name_map** arrgument which is passed??

**Comment by GokulNC** [comment]
Q1. `python Recognizer.py webcam` should work.
Check [this](https://github.com/GokulNC/Facial-Recognition-System/blob/master/Recognizer.py#L147)
No idea why it's not working for you.
Ensure you're in the `Facial-Recognition-System` folder before you run the script.

Q2. `label_name_map` contains the mapping from number to the person's name.
OpenCV can perform face recognition and return only labels (numbers), which we have to map to corresponding names.
Check the `Train_Images.py` to understand how it's done :)
It's dumped to the file `label_name_map_file` set in `configs.py`.

**Comment by Aashima-Gupta** [comment]
Hi,
It worked!  Thanks.

**Comment by hasnadr** [comment]
I have the same issue as @Aashima-Gupta I have tried and googled everything but I can't seem to find the solution? Please help.

**Comment by hasnadr** [comment]
Or maybe @Aashima-Gupta could show the error and how to fix it?? Thank you much appreciated.
